const companies = [
    "Reliance Industries",
    "TCS",
    "HDFC Bank",
    "ICICI Bank",
    "HUL",
    "Infosys",
    "ITC",
    "SBI",
    "Bharti Airtel",
    "Bajaj Finance",
    "LIC India",
    "Larsen & Toubro",
    "Kotak Mahindra Bank",
    "Asian Paints",
    "HCL Technologies",
    "Axis Bank",
    "Adani Enterprises",
    "Maruti Suzuki India",
    "Sun Pharma",
    "Titan Company",
    "Avenue Supermart",
    "Bajaj Finserv",
    "UltraTech Cement",
    "ONGC",
    "Nestle India",
    "Wipro",
    "NTPC",
    "Tata Motors",
    "JSW Steel",
    "Mahindra & Mahindra",
    "Power Grid Corporation of India",
    "Adani Ports",
    "Adani Green Enterprise",
    "LTIMindtree",
    "Tata Steel",
    "Coal India",
    "HDFC Life",
    "Siemens India",
    "Hindustan Zinc",
    "Bajaj Auto",
    "Pidilite Industries",
    "Indian Oil Corporation)",
    "Britannia",
    "Tech Mahindra",
    "IndusInd Bank",
    "Adani Power",
    "Varun Beverages",
    "Godrej Consumer",
    "Hindalco Industries",
    "Dabur India",
    "Divi's Laboratories",
    "Bank of Baroda",
    "Cipla",
    "Interglobe Aviation (Indigo)",
    "Dr Reddys Laboratories",
    "ABB India",
    "Ambuja Cements",
    "Bharat Electronics",
    "Eicher Motors",
    "Vedanta",
    "Cholamandalam Investment and Finance Company",
    "Adani Transmission",
    "Shree Cements",
    "SBI Card",
    "ICICI Prudentia",
    "Havells India",
    "Zomato",
    "Bajaj Holdings",
    "Bharat Petroleum Corporation",
    "TATA Consumer Products",
    "Gas Authority of India",
    "Mankind Pharmaceuticals",
    "Tata Power",
    "Marico",
    "United Spirits",
    "Apollo Hospital",
    "Adani Total Gas",
    "Torrent Pharmaceuticals",
    "Polycab",
    "Shriram Finance",
    "IDBI Bank",
    "Berger Paints",
    "Power Finance",
    "Macrotech Developers",
    "SRF",
    "ICICI Lombard General Insurance Company",
    "Jindal Steel & Power",
    "PNB",
    "Zydus Wellness",
    "Motherson Sumi Systems",
    "TVS Motor",
    "Info Edge",
    "CG Power",
    "Trent",
    "Union Bank of India",
    "Tube Investment",
    "MRF",
    "Hero MotoCorp",
    "ONE 97 COMMUNICATIONS (Paytm)",
    "JK Tyre & Industries   "
];

module.exports = companies;