const stockList = [
    { id: 1, name: "Reliance Industries", state: false },
    { id: 2, name: "TCS", state: false },
    { id: 3, name: "HDFC Bank", state: false },
    { id: 4, name: "ICICI Bank", state: false },
    { id: 5, name: "HUL", state: false },
    { id: 6, name: "Infosys", state: false },
    { id: 7, name: "ITC", state: false },
    { id: 8, name: "SBI", state: false },
    { id: 9, name: "Bharti Airtel", state: false },
    { id: 10, name: "Bajaj Finance", state: false },
    { id: 11, name: "LIC India", state: false },
    { id: 12, name: "Larsen & Toubro", state: false },
    { id: 13, name: "Kotak Mahindra Bank", state: false },
    { id: 14, name: "Asian Paints", state: false },
    { id: 15, name: "HCL Technologies", state: false },
    { id: 16, name: "Axis Bank", state: false },
    { id: 17, name: "Adani Enterprises", state: false },
    { id: 18, name: "Maruti Suzuki India", state: false },
    { id: 19, name: "Sun Pharma", state: false },
    { id: 20, name: "Titan Company", state: false },
    { id: 21, name: "Avenue Supermart", state: false },
    { id: 22, name: "Bajaj Finserv", state: false },
    { id: 23, name: "UltraTech Cement", state: false },
    { id: 24, name: "ONGC", state: false },
    { id: 25, name: "Nestle India", state: false },
    { id: 26, name: "Wipro", state: false },
    { id: 27, name: "NTPC", state: false },
    { id: 28, name: "Tata Motors", state: false },
    { id: 29, name: "JSW Steel", state: false },
    { id: 30, name: "Mahindra & Mahindra", state: false },
    { id: 31, name: "Power Grid Corporation of India", state: false },
    { id: 32, name: "Adani Ports", state: false },
    { id: 33, name: "Adani Green Energy", state: false },
    { id: 34, name: "LTIMindtree", state: false },
    { id: 35, name: "Tata Steel", state: false },
    { id: 36, name: "Coal India", state: false },
    { id: 37, name: "HDFC Life", state: false },
    { id: 38, name: "Siemens India", state: false },
    { id: 39, name: "Hindustan Zinc", state: false },
    { id: 40, name: "Bajaj Auto", state: false },
    { id: 41, name: "Pidilite Industries", state: false },
    { id: 42, name: "Indian Oil Corporation)", state: false },
    { id: 43, name: "Britannia", state: false },
    { id: 44, name: "Tech Mahindra", state: false },
    { id: 45, name: "IndusInd Bank", state: false },
    { id: 46, name: "Adani Power", state: false },
    { id: 47, name: "Varun Beverages", state: false },
    { id: 48, name: "Godrej Consumer", state: false },
    { id: 49, name: "Hindalco Industries", state: false },
    { id: 50, name: "Dabur India", state: false },
    { id: 51, name: "Divi's Laboratories", state: false },
    { id: 52, name: "Bank of Baroda", state: false },
    { id: 53, name: "Cipla", state: false },
    { id: 54, name: "Interglobe Aviation (Indigo)", state: false },
    { id: 55, name: "Dr. Reddy's Laboratories", state: false },
    { id: 56, name: "ABB India", state: false },
    { id: 57, name: "Ambuja Cements", state: false },
    { id: 58, name: "Bharat Electronics", state: false },
    { id: 59, name: "Eicher Motors", state: false },
    { id: 60, name: "Vedanta", state: false },
    { id: 61, name: "Cholamandalam Investment and Finance Company", state: false },
    { id: 62, name: "Adani Transmission", state: false },
    { id: 63, name: "Shree Cements", state: false },
    { id: 64, name: "SBI Cards", state: false },
    { id: 65, name: "ICICI Prudential", state: false },
    { id: 66, name: "Havells India", state: false },
    { id: 67, name: "Zomato", state: false },
    { id: 68, name: "Bajaj Holdings", state: false },
    { id: 69, name: "Bharat Petroleum Corporation", state: false },
    { id: 70, name: "Tata Consumer Products", state: false },
    { id: 71, name: "Gas Authority of India", state: false },
    { id: 72, name: "Mankind Pharmaceuticals", state: false },
    { id: 73, name: "Tata Power", state: false },
    { id: 74, name: "Marico", state: false },
    { id: 75, name: "United Spirits", state: false },
    { id: 76, name: "Apollo Hospitals", state: false },
    { id: 77, name: "Adani Total Gas", state: false },
    { id: 78, name: "Torrent Pharmaceuticals", state: false },
    { id: 79, name: "Polycab", state: false },
    { id: 80, name: "Shriram Finance", state: false },
    { id: 81, name: "IDBI Bank", state: false },
    { id: 82, name: "Berger Paints", state: false },
    { id: 83, name: "Power Finance", state: false },
    { id: 84, name: "Macrotech Developers", state: false },
    { id: 85, name: "SRF", state: false },
    { id: 86, name: "ICICI Lombard General Insurance Company", state: false },
    { id: 87, name: "Jindal Steel & Power", state: false },
    { id: 88, name: "PNB", state: false },
    { id: 89, name: "Zydus Wellness", state: false },
    { id: 90, name: "Motherson Sumi Systems", state: false },
    { id: 91, name: "TVS Motor", state: false },
    { id: 92, name: "Info Edge", state: false },
    { id: 93, name: "CG Power", state: false },
    { id: 94, name: "Trent", state: false },
    { id: 95, name: "Union Bank of India", state: false },
    { id: 96, name: "Tube Investments", state: false },
    { id: 97, name: "MRF", state: false },
    { id: 98, name: "Hero MotoCorp", state: false },
    { id: 99, name: "ONE 97 COMMUNICATIONS (Paytm)", state: false },
    { id: 100, name: "JK Tyre & Industries", state: false },
];

export default stockList;